### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\build_query()

### ISSUE THREAD

**Issue by HZMarico** [joshkulesza/php-flagr#2]
build_query will be removed in guzzlehttp/psr7:2.0

^7.3 IN your composer.json

```
"require": {
        "guzzlehttp/guzzle": "^6.2 || ^7.3"
    }
```

it can help with you

https://docs.aws.amazon.com/aws-sdk-php/v3/api/function-GuzzleHttp.Psr7.build_query.html

**Comment by joshkulesza** [comment]
Thanks for raising this.

This project is generated using swagger-codegen.

I'll update the deps to prevent use in newer versions of guzzlehttp til swgger-codegen produces an output with support for  versions without build_query
